
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwxoqssgkuxduskwjnce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3eG9xc3Nna3V4ZHVza3dqbmNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMTk5MzQsImV4cCI6MjA1NzY5NTkzNH0.K_7RX74ZjuNV40RMR4AKnB6mMwnkwN1tmvcPgmavjPY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
